<template>
  <a-flex gap="middle" wrap="wrap">
    <product-blank v-if="productsStore.isLoading" />

    <product-item
      :key="product.id"
      :product="product"
      @buy="onBuyClick"
      @click="onProductClick(product)"
      v-else
      v-for="product of productsStore.productList"
    />
  </a-flex>
</template>

<script setup lang="ts">
import { onBeforeMount, watch } from 'vue';
import { useRouter } from 'vue-router';

import ProductBlank from './ProductBlank.vue';
import ProductItem from './ProductItem.vue';
import { useProductsStore, useShoppingCartStore } from '@app/store';
import { Product } from '#types/product';

const props = defineProps({
  categoryId: {
    type: String,
    required: true,
  },
});

const router = useRouter();
const productsStore = useProductsStore();
const cartStore = useShoppingCartStore();

function getProductKey(product: Product) {
  return `${product.autogeneratedSlug}-p${product.id}`;
}

function onProductClick(product: Product) {
  const key = getProductKey(product);

  router.push({ name: 'product', params: { productId: key } });
}

function onBuyClick(product: Product) {
  cartStore.addToCart(product);
}

watch(
  () => props.categoryId,
  () => {
    productsStore.getProducts(props.categoryId || 'home');
  },
);

onBeforeMount(() => {
  productsStore.getProducts(props.categoryId || 'home');
});
</script>
