<template>
  <a-flex :class="$style.listWrapper" gap="middle" wrap="wrap">
    <category-blank v-if="categoriesStore.isLoading" />

    <router-link
      :to="{ name: 'products', params: { categoryId: `${category.autogeneratedSlug}-c${category.id}` } }"
      v-else
      v-for="category of categoriesStore.categoryList"
    >
      <category-item :alt="category.alt.main" :key="category.id" :src="category.thumbnailUrl">
        {{ category.name }}
      </category-item>
    </router-link>
  </a-flex>
</template>

<script setup lang="ts">
import { onBeforeMount, watch } from 'vue';

import CategoryBlank from './CategoryBlank.vue';
import CategoryItem from './CategoryItem.vue';
import { useCategoriesStore } from '@app/store';

const props = defineProps({
  categoryId: {
    type: String,
    required: true,
  },
});

const categoriesStore = useCategoriesStore();

watch(
  () => props.categoryId,
  () => {
    categoriesStore.getCategories(props.categoryId || '0');
  },
);

onBeforeMount(() => {
  categoriesStore.getCategories(props.categoryId || '0');
});
</script>

<style lang="css" module>
.listWrapper {
  padding-bottom: 32px;
}
</style>
