interface ImageDetails {
  url: string;
  width: number;
  height: number;
}

interface Translations {
  [key: string]: string;
}

interface Alts {
  main: string;
  [key: string]: string;
}

interface Category {
  id: number;
  parentId: number | undefined;
  orderBy: number;
  hdThumbnailUrl: string;
  thumbnailUrl: string;
  imageUrl: string;
  originalImageUrl: string;
  originalImage: ImageDetails;
  name: string;
  thumbnail: ImageDetails;
  nameTranslated: Translations;
  origin: string;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  enabledProductCount: number;
  description: string;
  descriptionTranslated: Translations;
  enabled: boolean;
  productIds: number[];
  seoTitle: string;
  seoTitleTranslated: string;
  seoDescription: string;
  seoDecriptionTranslated: string;
  alt: Alts;
}

interface CategorySearchResult {
  total: number;
  count: number;
  offset: number;
  limit: number;
  items: Category[];
}

export type { Category, CategorySearchResult };
